### model
model_name_or_path: /mnt/data3/models/DeepSeek-V2-Lite-Chat
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: west_train
template: deepseek
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /mnt/data/lpl/kernel_new_test_adapter/Kllama2_deepseekV2_WEST_ALL
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 0.1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
disable_gradient_checkpointing: true
resume_from_checkpoint: null

### ktransformers
use_kt: true                    # 启用 KTransformers MoE 后端
kt_backend: AMXBF16            # AMX 后端类型: AMXBF16 或 AMXInt8
kt_num_threads: 60              # CPU 线程数
kt_tp_enabled: false             # 启用 NUMA 张量并行
kt_num_gpu_experts: 0           # GPU 上运行的专家数量 (0=全部在CPU, Phase 2 功能)
kt_moe_lora_device: gpu         # MoE LoRA 参数位置: gpu (推荐) 或 cpu (暂不支持)
# kt_weight_path: /mnt/data3/models/DeepSeek-V2-Lite-INT8          # 预处理权重路径 (可选，用于 INT4/INT8)

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
