### model
model_name_or_path: /mnt/data/models/Qwen3-30B-A3B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 12
lora_target: all

### dataset
dataset: west_train
template: deepseek
cutoff_len: 20480
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /mnt/data/hxx/kernel_new_test_adapter/Kllama_test_qwen3_30_WEST_ALL_cpu
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 0.005
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false

ddp_timeout: 180000000
disable_gradient_checkpointing: true
resume_from_checkpoint: null

# kt_config:
#   enabled: true
#   kt_backend: AMXINT8
#   kt_num_threads: 64
#   kt_tp_enabled: true
#   kt_threadpool_count: 2
#   kt_num_gpu_experts: 0
#   kt_use_lora_experts: false
#   kt_lora_expert_num: 2
#   kt_lora_expert_intermediate_size: 1024
#   lora_rank: 8
#   lora_alpha: 16
#   model_max_length: 15360
  # kt_skip_expert_loading: true
  # kt_weight_path: /mnt/data/hxx/q3-235-i8
### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500


layer_debug: true                                                                                                                                                                       
layer_debug_output_dir: /mnt/data/hxx/layer_outputs_qw3-a30-cpu                                                                                                                           
layer_debug_save_forward: true                                                                                                                                                          
layer_debug_save_backward: true                                                                      
layer_debug_save_input: false                                                                                                                                                           
layer_debug_save_steps: "0,1,2,3,20,40"                                                                                                    
layer_debug_prefix: kt_debug                                                                                                                                                            
layer_debug_verbose: false   