### model
model_name_or_path: Qwen/Qwen3.5-397B-A17B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: kt_attention
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.1
kt_lora_variant: altlora_attn
altlora_reg: 1.0e-5
altlora_beta1: 0.9
altlora_first_factor: B
altlora_switch_every_optimizer_steps: 1

### dataset
dataset: identity,alpaca_en_demo
template: qwen3_5
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/KT_FT_qwen35Moe_altlora_attn
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
optim: adamw_torch
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### ktransformers
use_kt: true
kt_model_max_length: 12288
# kt_weight_path: /path/to/Qwen3.5-MoE-AMXINT8
