### Commonsense Benchmark - Qwen3-30B-A3B LoRA SFT (Non-KT)
### Multi-dataset single adapter training for commonsense reasoning tasks

### model
model_name_or_path: /mnt/data3/models/Qwen3-30B-A3B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset (8 commonsense datasets merged)
dataset: cs_arc_challenge,cs_arc_easy,cs_boolq,cs_hellaswag,cs_openbookqa,cs_piqa,cs_social_iqa,cs_winogrande
template: qwen3_nothink
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen3-30b-a3b/lora/commonsense
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval (validation set configuration)
eval_dataset: cs_arc_challenge_val,cs_arc_easy_val,cs_boolq_val,cs_hellaswag_val,cs_openbookqa_val,cs_piqa_val,cs_social_iqa_val,cs_winogrande_val
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
